FROM golang:1.20-alpine as buildbase

WORKDIR /go/src/github.com/rarimo/rarime-link-svc
COPY vendor .
COPY . .

ENV GO111MODULE="on"
ENV CGO_ENABLED=0
ENV GOOS="linux"

RUN go build -o /usr/local/bin/rarime-link-svc github.com/rarimo/rarime-link-svc

###

FROM alpine:3.9 as calpine

RUN apk add --no-cache ca-certificates

FROM calpine

COPY --from=buildbase /usr/local/bin/rarime-link-svc /usr/local/bin/rarime-link-svc
ENTRYPOINT ["rarime-link-svc"]
